### PR TITLE
Td/input

### PR DESCRIPTION
**Pull request by tmdawson23**
## Checklist before requesting a review
- [x] I have performed a self-review of the code
- [x] I have added all proper testing for the components included in this branch

### CODE REVIEW

**Comment by pdreed** [comment]
@tmdawson23 need to add the proper index file within the Input folder and update the index file to the components folder

**Comment by pdreed** [comment]
@tmdawson23 we may need to work on reducing the width of the input area

**Comment by pdreed** [comment]
@tmdawson23 the storybook test example is not properly rendering the label - it is appearing to the left of the input. Also, no input area is rendering

**Comment by tmdawson23** [comment]
> the storybook test example is not properly rendering the label - it is appearing to the left of the input. Also, no input area is rendering

@pdreed The label now appears above the input area 

> we may need to work on reducing the width of the input area

@pdreed I reduced the width of the input area box

> need to add the proper index file within the Input folder and update the index file to the components folder

@pdreed Added index file & updated index file to components folder

**Pull request closed without merging**
